# example header file;
# put this in your project directory
header = '''
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      2024-01-01
// @description  try to take over the world!
// @author       You
// @match        https://example.com
// @grant        none
// ==/UserScript==
'''